version: "3.1"

services:
  nuxt:
    build: ./app/
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    command: npm run start
    environment:
      HOST: 0.0.0.0
